### ISSUE TITLE
importing plot module

### ISSUE THREAD

**Issue by rafazh** [pynbody/pynbody#217]
After performing a local installation of PynBody, I cannot import some of its modules (a). This still allows me to do some analysis (b), but fails at some functions calls (c).

Prior to that, I used to work with pynbody v0.19 and the issue was not raised (for example, see below).

(a):

``` python
In [1]: import matplotlib.pyplot as plt
In [2]: import pynbody as pb
/home/ics/rafael/.local/lib/python2.6/site-packages/pynbody/__init__.py:119: RuntimeWarning: Unable to import plotting package (missing matplotlib or running from a text-only terminal? Plotting is disabled.
  "Unable to import plotting package (missing matplotlib or running from a text-only terminal? Plotting is disabled.", RuntimeWarning)
```

(b):

``` python
In [3]: sim = pb.load("2bh.00000")
In [4]: sim.physical_units()
In [5]: print sim.g['pos']
[[ -2.71439762e-02   3.00420589e-02   9.04019736e-06]
 [  5.17747421e-02   5.28466530e-02  -5.50682259e-03]
 [ -2.45008602e-02   3.38154793e-02  -8.29571342e-03]
 ..., 
 [  2.62798519e-02   2.02210217e-02  -2.00874686e-03]
 [  2.33617363e-02  -8.60407734e-03  -1.70528460e-03]
 [ -7.91108170e-02  -4.59713554e-02  -8.51852512e-03]]
```

(c)

``` python
In [6]: img=pb.plot.sph.image(sim.g, qty="rho", units="Msol pc^-2", xy_units='pc', width=width, noplot=True)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-976d17811056> in <module>()
----> 1 img=pb.plot.sph.image(sim.g, qty="rho", units="Msol pc^-2", xy_units='pc', width=width, noplot=True)
AttributeError: 'module' object has no attribute 'plot'
```

If any of you got an idea on what might be the issue, let me know. Also, as suggested by Rok, I went to check if I could do some imports from the [**init.py**](https://github.com/pynbody/pynbody/blob/master/pynbody/plot/__init__.py) file:

``` python
In [7]: import pynbody.generic
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-9adc6495a684> in <module>()
----> 1 import pynbody.generic

ImportError: No module named generic
```

Any hint is appreciated.

Cheers,
Rafael

PS.: It might be a specific installation related problem. I used to use v0.19 just by referencing to the package in the python search path (by appending pynbody folder to PYTHONPATH env variable). Cython was not installed by then.

So, what has changed:
    1. I installed the latest releases of cython, numpy, matplotlib and pynbody using the command line:
        python setup.py install --user
    building whenever necessary.
    2. The entry to PynBody v0.19 was removed from python's search path to avoid conflict.
